[build]
  base = "apps/stock-outwards"
  command = "cd ../.. && npm install && npm run build:stock-outwards"
  publish = "apps/stock-outwards/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
